hik:
  app_key: e69b05304140449997738272d2afa7cc
  app_secret: 2bcca73bb23c65af91f5fcd79e713409
wx:
  #小程序appid
  appid: wxdee2b19db3be8517
  #小程序秘钥
  secret: 99887628a67e7d8a23d4d8410bcf47a1
  #商户号
  mch_id: 1631185974
  #商户秘钥
  mch_key: QAZ12wsxcdQAZ12wsxcdQAZ12wsxcd21
  #apiV2 秘钥
  apiV2_secret: QBmbglkLDeZrVDYrfj75zN2yiTY8BToI
  #apiV3 秘钥
  apiV3_secret: ERuAkVmMaiYRiFNNaNMyvnuNEQHksRBC
  #商户证书序列号
  cert_serial: 73C3AEF33ECD9C7E71FA11C155BFAF99694230F8
  cert_private_pem_path: apiclient_key.pem
  cert_public_pem_path: apiclient_cert.pem
  #公众号appid
  official_appid: wxdee2b19db3be8517
  #公众号秘钥
  official_secret: 99887628a67e7d8a23d4d8410bcf47a1
agora:
  appid: 7be11df0b1b547e0b67b7960a4d7ff05
  app_certificate: 7066736b8f59453fb3e55f59361f987a
shouqianba:
  app_id: 2022101900005102
  vendor_sn: 91801644
  vendor_key: 039624f6b802829dc908669a07247535
  cis_app_id: 28cis46221027
  cis_client_id: 47105a951745453c9fe027f75cdf33db
  shouqb_cis_pub_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuWsSRXr6f8C5J76tkQs1tZdAHnpfax0Pyr37MluyPt8lJe4oJrGLKUxKzrpcwjD0YUnMwQPpq6rBRl6gGN0fVZo2nNfdWTDcqrKNW8W4ECvxERd7ABEdiwgaxGZ4dyyCn+Ttnkzyz88+KAOoa25wMQutPxKsJ6CUYuHwUzeH52QpoVpTbCFtNyA37eBogY8oAKKakNPWBbXok4P1ebU+sc1ee3rKzCzmPo6yVD6moNaEQ8TFV+vgSeAbcif7cqU8D69x5UdemfhKbIUHMgDVIv/Ij3u9lep4op0pnE/riYsanSn+q4LiMQj9QJe02+99NKZNio7gJwamzYzB2jWnQwIDAQAB
  shouqb_pub_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5+MNqcjgw4bsSWhJfw2M+gQB7P+pEiYOfvRmA6kt7Wisp0J3JbOtsLXGnErn5ZY2D8KkSAHtMYbeddphFZQJzUbiaDi75GUAG9XS3MfoKAhvNkK15VcCd8hFgNYCZdwEjZrvx6Zu1B7c29S64LQPHceS0nyXF8DwMIVRcIWKy02cexgX0UmUPE0A2sJFoV19ogAHaBIhx5FkTy+eeBJEbU03Do97q5G9IN1O3TssvbYBAzugz+yUPww2LadaKexhJGg+5+ufoDd0+V3oFL0/ebkJvD0uiBzdE3/ci/tANpInHAUDIHoWZCKxhn60f3/3KiR8xuj2vASgEqphxT5OfwIDAQAB
  ct_priv_key: MIIEpAIBAAKCAQEAii4xpHDjdykqK3vEKl+B01boxtV3Q49EEh9MVOSC4RqiiyfjKLVDYUuBYR4PRudKR/CgdHfLpDAAjQ+Z8rlJrq3ifRGURRG6uH4VEexiiPc2e7GeIH0KBLsLhgDCdvChSD8N4ywK0dhfgOLguYDY87b521TNp8FODg0fidtRFxGYXvjzx9aBVIxG4/6HFMOa1tB1SVzXm7oh6INTT1+e5BQniiDlKUHmUDQAz/QXmoHMruJFfi6eJHfMZDYi4xJUK8boja4MTcW3+E2YoxIMF/bC39wvgubqMGrjK2C7Ox5KGITidf0Nv56xRIHKTeEgh/Q8rKmDLVdQE93eJkx3ewIDAQABAoIBAAx2hCW3xNxfix0m6ZeEy7nbEd21LS+bwWD9D65sed2BwH1amKN4Td59p+qxgmE7xThd3KsEjwp9Bd+zM4hv69RkfJQZPM1J/xRa0t2t+2ktGu3nJEL75CZvFGf+s4t0wqc4gLEnrMYmhN6kF+7DT04UB88fg/kId1jPGDQf4t14p9g0m9fRI3ttI9JIK0ICC9WzL1c6ur67UgiABDMDuB7eNL5xf+EMAGLGHRl7JqbB0B5nQkx6BKM3u5Jy+SCAXtT478Qlznmhg3aANBRPTmbaKvrVtv5pF1qH/D5hL5uMutVxPh+9Ow+5XhvLX6eUPfpQDuzDqIZeq0OOfzxTyyECgYEAw7ZlVKxscUpeBsdQqo2CRVFDymekzyTHOL7N5aJQ3uuRmL6axldb4gbfUnrlyhj09uujcUFhOOoIy12rKCBtzsRONCHR3Rl1ZAyx0andqismM1KEN7EZ2MKzxa+LkAn9D9OtPLx9+lO0/0cTnod7kR+j2BSwlRfT82DzilRv6msCgYEAtL7njWslqib/YRhkV7EUIE5JRtzzq7hMqEsvOgHGEkagHIR8iP14/TGIT5brCx4BeMTJxwopCFHvNT+ZxCuaMvjewJZoepYmRUgAUNjsMuJwa/7IiSjOKTi7zWOw4FJrfHAPwFxHphyCPLOyiV4zFLtsL+ToSWvzHYtibrjqCzECgYBVt+1pyJs2g3vrPCD4kkIcWht26y4kC9e14twLV6xT9pkubU0c0eZMePYXCfzbJ1MjUtGjKR+L7fUsHTp5uLpfdVtLOgTQ8fWYfHblfaC4h22TzPBb9BV9+skCLIDT9YwBApU9pNEIcuEzbc4KAQz94v3ABk/Q/T63uh7w10qtQQKBgQCm/IjpOsi9fvIKPoLWEZ/KiQliEth9GfSYt32WVfUtBVr/fdegqK2THqQVBBV7W+l4LjdNULHAIhKiW3QwrSf1V8BUpaE5QGdzMqY4C3GNQW8kF2wmbDCsHOJFS4kqdnsfqFilG5yGd2hLtKmKCCGhUdcOGKoSy0z9Sr1SFj0EwQKBgQC5Lhr//koQ/Q3XLQtOIw3FYPuJBlwyWSaPmai+4vsI/jj1EKKK/cwNulZW2A1ZPxFKR8O7uvkWJuQyniwJcvq4LVPxtnk3ol3FbDgujoySA/1mpHnUg+aHs82kz1J8AyKcSwPHWohfMM3WG0W0gECxe3lXgSuLoctDGlwi+eae0w==
  ct_pub_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAii4xpHDjdykqK3vEKl+B01boxtV3Q49EEh9MVOSC4RqiiyfjKLVDYUuBYR4PRudKR/CgdHfLpDAAjQ+Z8rlJrq3ifRGURRG6uH4VEexiiPc2e7GeIH0KBLsLhgDCdvChSD8N4ywK0dhfgOLguYDY87b521TNp8FODg0fidtRFxGYXvjzx9aBVIxG4/6HFMOa1tB1SVzXm7oh6INTT1+e5BQniiDlKUHmUDQAz/QXmoHMruJFfi6eJHfMZDYi4xJUK8boja4MTcW3+E2YoxIMF/bC39wvgubqMGrjK2C7Ox5KGITidf0Nv56xRIHKTeEgh/Q8rKmDLVdQE93eJkx3ewIDAQAB
wiegand:
  http_host: 127.0.0.1:61080
  ws_host: 127.0.0.1:61081