spring:
  config:
    import:
    - classpath:/common/common.yml
    - classpath:/test/druid.yml
    - classpath:/test/rocketmq.yml
    - classpath:/test/partner.yml
    - classpath:/test/redis.yml

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /admin-api
  # undertow 配置
  undertow:
    # HTTP post内容的最大大小。当值为-1时，默认值为大小是无限的
    max-http-post-size: -1
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 512
    # 是否分配的直接内存
    direct-buffers: true
    threads:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      io: 8
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker: 256
    session:
      timeout: 30000

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true


# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: onv8PKZNWk11L8NfRF21pigkWVblYostI8rIRnZiHMBqxlcbyXk5nmvtHzn1747p
  # 令牌有效期（单位分钟，默认7天）
  expireTime: 10080
