adapay:
  debug: true
  prodMode: true
  apiKey: "api_live_45eb98d2-9f47-4298-b6f7-88e736df0d80"
  mockApiKey: "api_test_9d0e0f5e-2b88-4b93-849a-ace775e8845c"
  appId: "app_f257335e-b45a-4365-8fc5-6685c985dc67"
  wxAppId: "wx572d6b1bf8a7e139"
  rsaPrivateKey: "MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBALs9GN+5Ni4aaPCs
  fo+b4reLNROFOlXenhTI+b6+3gA9Hy6R3cpJNzeJfLTBk+sXu4uirp2cAD+D78Oq
  3zncd7g0E3hnqBYW/+PnlE9PnjiApCssqfZeBYtqO7wRTIdILqgYcNBE9HjKNBZC
  NXvl4/HyOIWoyYXpBYENTG8598vBAgMBAAECgYAUXVjPPH3AFe9D/f7l77aA8Asd
  zGfD3yqiaBmBvZC3xe4WSpcs4Tm4OKPvpP5Jm5MyZMdJLSZ5wgfZ6EPPL0N1/cd8
  tM7cIjujO8eQCD3OdqzOfRCTRP1Yp2l/UDMtNMktP3g8tQw9fFaDZOQZX6Rm2D0c
  FCcPJPmdbHLJc+bpYQJBAOUTxjgOwnSQYJ+i83GAvdF/fzzT7LTf0eyJIF0n+dgN
  XVXGe2DgW1OvLv0RN3O6rZ0BhksKGGW19JB8SBQZw+cCQQDRPoeCN+RnQaILgXSV
  gFzt8se9TUM2Mr0OJCT7BVP50DIHIyRuiBm1AsIVdxPBQOGdw6DLGmOZaCwEtO7h
  eP4XAkEAt2uk7F/NDb5Iz6mPGZPG6UcYHyFlR9Jq6OVHV6/ZmkfhMvwQ8BnUpmX/
  zrwJVY3k03FUESONM2uE3mfU4ttagwJBAIF4RlKdkNcPNlwWKvQCa/3TliGct/TG
  KlKgrL0hi9dsKjheV0GJNxbYcQzlFDUklzWOAWUKnAwk9++loJWkztsCQQChjQ/B
  Xar1fdumoMdDxXvgK7ymasUGi04BogmwbfuDcTzCTqxBa6W29BFjfclMJT7Pjp9t
  Etz+InShFTzMPgto"